apiVersion: v1
kind: Service
metadata:
  name: my-postgres-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: my-postgresql